server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: property.estate001@gmail.com
    password: eocmhtrnjmfhvvgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


